### ISSUE TITLE
Generation failed because syntax error

### ISSUE THREAD

**Issue by Simply007** [Enngage/KenticoCloudModelGeneratorUtility#1]
When a user try to generate the code using the utility, exception is raised:
C:\Users\ondrejch\AppData\Roaming\npm\node_modules\kentico-cloud-model-generator-utility\lib\ts-generator.js:157
function mapFieldTypeToName(fieldType, ) {
                                       ^
SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\ondrejch\AppData\Roaming\npm\node_modules\kentico-cloud-model-generator-utility\index.js:5:21)

**Comment by Simply007** [comment]
I am not able to fix thi issue, neither create a pull request.

Fix is just delete a comma in function signature: mapFieldTypeToName function in /lib/ts-generator.js file.

**Comment by Enngage** [comment]
Thanks a lot for letting me know! Not sure where it came from. Hopefully it should be fixed now (https://github.com/Enngage/KenticoCloudModelGeneratorUtility/commit/99b4382785bca610dc7b12c4f4faa3b8f12b7c79)
